#! /bin/sh

set -ex

srcdir="$(dirname "$0")"
test -z "$srcdir" && srcdir=.

cd "$srcdir"

[ -f freestanding-toolchain ] || ( curl -Lo freestanding-toolchain https://github.com/mintsuki/freestanding-toolchain/raw/trunk/freestanding-toolchain && chmod +x freestanding-toolchain )
[ -d freestanding-headers ] || git clone https://github.com/mintsuki/freestanding-headers.git --depth=1
[ -d libgcc-binaries ] || git clone https://github.com/mintsuki/libgcc-binaries.git --depth=1
[ -f src/limine.h ] || curl -Lo src/limine.h https://github.com/limine-bootloader/limine/raw/trunk/limine.h
[ -d src/flanterm ] || git clone https://github.com/mintsuki/flanterm.git src/flanterm --depth=1
if ! [ -d src/printf ]; then
    mkdir src/printf
    curl -Lo src/printf/printf.c https://github.com/eyalroz/printf/raw/master/src/printf/printf.c
    curl -Lo src/printf/printf.h https://github.com/eyalroz/printf/raw/master/src/printf/printf.h
fi

MLIBC_VERSION=3b38e0398a5e85b6602a3bf7922dc35988b20594

if ! [ -d mlibc-headers ]; then
    curl -Lo mlibc.tar.gz https://github.com/mintsuki/mlibc/archive/${MLIBC_VERSION}.tar.gz
    tar -xf mlibc.tar.gz
    mkdir mlibc-build
    cd mlibc-build
    meson setup \
        --cross-file ../cross_file.txt \
        --prefix=/ \
        -Dheaders_only=true \
        -Ddisable_crypt_option=true \
        -Ddisable_iconv_option=true \
        -Ddisable_intl_option=true \
        ../mlibc-${MLIBC_VERSION}
    ninja
    mkdir ../mlibc-headers-out
    DESTDIR="$(cd ../mlibc-headers-out && pwd -P)" ninja install
    cd ..
    mv mlibc-headers-out/include mlibc-headers
    rm -rf mlibc.tar.gz mlibc-${MLIBC_VERSION} mlibc-build mlibc-headers-out
fi

autoreconf -fvi -Wall

AUTOMAKE_LIBDIR="$(automake --print-libdir)"

cp "${AUTOMAKE_LIBDIR}/INSTALL" ./

mkdir -p build-aux
eval "$(grep 'ac_aux_files="' configure)"
for f in $ac_aux_files; do
    cp "${AUTOMAKE_LIBDIR}/$f" ./build-aux/
done
